from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen.canvas import Canvas


ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "fixtures/diagnosis/v0.2"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate_into(root: Path) -> dict:
    root.mkdir(parents=True, exist_ok=True)
    short_note = root / "short-note.md"
    short_note.write_text("# Short Note\n\nInspect this short document.\n", "utf-8", newline="\n")

    duplicate = (
        "This intentionally repeated paragraph contains enough normalized characters "
        "to exercise stable duplicate-block evidence without using private source text."
    )
    structural = root / "structural-traps.md"
    structural.write_text(
        "\n".join(
            [
                "## Structural Traps",
                "",
                "This line contains one replacement character: \ufffd.",
                "",
                duplicate,
                "",
                duplicate,
                "",
                "#### Jumped Heading",
                "",
                "A final unique paragraph keeps this diagnostic fixture readable.",
                "",
            ]
        ),
        "utf-8",
        newline="\n",
    )

    repeated = root / "repeated-margin.pdf"
    canvas = Canvas(str(repeated), pagesize=letter, invariant=1, pageCompression=1)
    canvas.setAuthor("tiny-corpus-workbench contributors")
    canvas.setCreator("tools/generate_diagnosis_fixtures.py")
    canvas.setTitle("Repeated Margin Diagnostic Fixture")
    for page in range(1, 4):
        canvas.setFont("Helvetica", 10)
        canvas.drawString(72, 725, "CONTROLLED REPEATED MARGIN TEXT")
        canvas.drawString(
            72,
            640,
            f"Unique body text for diagnostic page {page}: TCW-DIAG-PAGE-{page}.",
        )
        canvas.drawString(72, 18, "REPEATED FURNITURE NEGATIVE CASE")
        canvas.showPage()
    canvas.save()

    records = []
    for identifier, path, expected in (
        ("short-note", short_note, ["TCW-D002"]),
        ("structural-traps", structural, ["TCW-D003", "TCW-D004", "TCW-D005"]),
        ("repeated-margin", repeated, ["TCW-D007"]),
    ):
        records.append(
            {
                "id": identifier,
                "path": f"fixtures/diagnosis/v0.2/{path.name}",
                "size": path.stat().st_size,
                "sha256": digest(path),
                "license": "CC0-1.0",
                "expected_rules": expected,
            }
        )
    registry = {
        "schema_version": "tcw.diagnosis-fixture-registry/v0.2",
        "generator": "tools/generate_diagnosis_fixtures.py",
        "fixtures": records,
    }
    (root / "fixtures.json").write_text(
        json.dumps(registry, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        "utf-8",
        newline="\n",
    )
    return registry


def snapshot(root: Path) -> dict[str, bytes]:
    return {
        path.name: path.read_bytes()
        for path in sorted(root.iterdir())
        if path.is_file()
    }


def main() -> int:
    arguments = argparse.ArgumentParser()
    arguments.add_argument("--check", action="store_true")
    args = arguments.parse_args()
    if not args.check:
        generate_into(DESTINATION)
        return 0
    with tempfile.TemporaryDirectory() as first, tempfile.TemporaryDirectory() as second:
        first_root, second_root = Path(first), Path(second)
        generate_into(first_root)
        generate_into(second_root)
        if snapshot(first_root) != snapshot(second_root):
            raise SystemExit("diagnosis fixture generation is not byte-deterministic")
        if snapshot(first_root) != snapshot(DESTINATION):
            raise SystemExit("committed diagnosis fixtures differ from generated bytes")
    print("diagnosis fixture generation is byte-deterministic and matches committed files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
